version: 43
jobs:
- name: Git mirror push
  steps:
  - type: PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALWAYS
    optional: false
  triggers:
  - type: TagCreateTrigger
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Windows Testing
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: run unit tests
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild test -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild mock publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: develop master
    userMatch: anyone
  jobDependencies:
  - jobName: Windows Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Ubuntu Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: ubuntu x64 tests
    runInContainer: true
    image: docker.io/ubuntu:24.04@@sha256:786a8b558f7be160c6c8c4a54f9a57274f3b4fb1491cf65146521ae77ff1dc54
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@/ci
        
        apt update; apt install curl -y
        chmod +x ./mise
        ./mise settings experimental=true
        ./mise bootstrap --yes
        ./mise test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Fedora Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: fedora-44 x64 tests
    runInContainer: true
    image: docker.io/fedora:44@@sha256:6c75d5bf57cb0fa5aa4b92c6a83c86c791644496d9ac230de7711f5b8ec3b898
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@/ci

        chmod +x ./mise
        ./mise settings experimental=true
        ./mise bootstrap --yes
        ./mise test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish branch
  jobExecutor: publish-agents
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
