version: 43
jobs:
- name: Git mirror push
  steps:
  - type: PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALWAYS
    optional: false
  triggers:
  - type: TagCreateTrigger
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Windows Testing
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: run unit tests
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild test -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild mock publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: develop master
    userMatch: anyone
  jobDependencies:
  - jobName: Windows Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Ubuntu Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: ubuntu x64 tests
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:8.0.415-noble-amd64@@sha256:a0f438b4cfbfd28cefa865facd9d1359732f8fb266a83a515a3634b0e8ac4f0b
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@

        export DOTNET_ROOT=$(pwd)/.dotnet
        export PATH="$PATH:${DOTNET_ROOT}:$HOME/.dotnet/tools"
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
        bash ci/scripts/linux-setup-amd64.sh install

        vnbuild test -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Fedora Tests
  jobExecutor: docker
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: fedora-43 x64 tests
    runInContainer: true
    image: docker.io/fedora:43@@sha256:2ad3073554aef41c15b2c52e968ec0540c931bc3dab8c599ca6eb6f32f3f2d14
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@

        export DOTNET_ROOT=$(pwd)/.dotnet
        export PATH="$PATH:${DOTNET_ROOT}:$HOME/.dotnet/tools"
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
        bash ci/scripts/linux-setup-amd64.sh install

        vnbuild test -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish branch
  jobExecutor: publish-agents
  steps:
  - type: CommandStep
    name: checkout
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
