version: 37
jobs:
- name: Git mirror push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/noscrypt.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: noscrypt
  - !BranchUpdateTrigger
    projects: noscrypt
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Windows Testing
  jobExecutor: windows
  steps:
  - !CommandStep
    name: checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@ @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild test -i @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@ @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --sign
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop master
  jobDependencies:
  - jobName: Windows Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Ubuntu Testing
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: true
    image: noscrypt-ubuntu:latest
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Publish on tag
  jobExecutor: windows
  steps:
  - !CommandStep
    name: checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @tag@ @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
